package TicTakTicketCORBA.corbaTTT;

/**
* TicTakTicketCORBA/corbaTTT/CorbaConterollerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaTTT.idl
* Dienstag, 19. November 2013 11:44 Uhr MEZ
*/

public final class CorbaConterollerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public TicTakTicketCORBA.corbaTTT.CorbaConterollerInterface value = null;

  public CorbaConterollerInterfaceHolder ()
  {
  }

  public CorbaConterollerInterfaceHolder (TicTakTicketCORBA.corbaTTT.CorbaConterollerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TicTakTicketCORBA.corbaTTT.CorbaConterollerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TicTakTicketCORBA.corbaTTT.CorbaConterollerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TicTakTicketCORBA.corbaTTT.CorbaConterollerInterfaceHelper.type ();
  }

}
