package TicTakTicketCORBA.corbaTTT;


/**
* TicTakTicketCORBA/corbaTTT/StructVernastaltung.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaTTT.idl
* Dienstag, 19. November 2013 11:44 Uhr MEZ
*/

public final class StructVernastaltung implements org.omg.CORBA.portable.IDLEntity
{
  public int vid = (int)0;
  public String vDatum = null;
  public String vName = null;
  public String vOrt = null;
  public String kuenstler = null;

  public StructVernastaltung ()
  {
  } // ctor

  public StructVernastaltung (int _vid, String _vDatum, String _vName, String _vOrt, String _kuenstler)
  {
    vid = _vid;
    vDatum = _vDatum;
    vName = _vName;
    vOrt = _vOrt;
    kuenstler = _kuenstler;
  } // ctor

} // class StructVernastaltung
