package TicTakTicketCORBA.corbaTTT;

/**
* TicTakTicketCORBA/corbaTTT/StructKarteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaTTT.idl
* Dienstag, 19. November 2013 11:44 Uhr MEZ
*/

public final class StructKarteHolder implements org.omg.CORBA.portable.Streamable
{
  public TicTakTicketCORBA.corbaTTT.StructKarte value = null;

  public StructKarteHolder ()
  {
  }

  public StructKarteHolder (TicTakTicketCORBA.corbaTTT.StructKarte initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TicTakTicketCORBA.corbaTTT.StructKarteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TicTakTicketCORBA.corbaTTT.StructKarteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TicTakTicketCORBA.corbaTTT.StructKarteHelper.type ();
  }

}
