package TicTakTicketCORBA.corbaTTT;


/**
* TicTakTicketCORBA/corbaTTT/StructKarte.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaTTT.idl
* Dienstag, 19. November 2013 11:44 Uhr MEZ
*/

public final class StructKarte implements org.omg.CORBA.portable.IDLEntity
{
  public int kartenId = (int)0;
  public String reihe = null;
  public int platz = (int)0;

  public StructKarte ()
  {
  } // ctor

  public StructKarte (int _kartenId, String _reihe, int _platz)
  {
    kartenId = _kartenId;
    reihe = _reihe;
    platz = _platz;
  } // ctor

} // class StructKarte
