package TicTakTicketCORBA.corbaTTT;


/**
* TicTakTicketCORBA/corbaTTT/StructKategorie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaTTT.idl
* Dienstag, 19. November 2013 11:44 Uhr MEZ
*/

public final class StructKategorie implements org.omg.CORBA.portable.IDLEntity
{
  public int kategId = (int)0;
  public String katName = null;
  public double katPreis = (double)0;

  //typdef fixed<9,2> katPreis;  wird von idlj nicht unterstuetzt
  public int freiePlaetze = (int)0;
  public int ermaessigung = (int)0;

  public StructKategorie ()
  {
  } // ctor

  public StructKategorie (int _kategId, String _katName, double _katPreis, int _freiePlaetze, int _ermaessigung)
  {
    kategId = _kategId;
    katName = _katName;
    katPreis = _katPreis;
    freiePlaetze = _freiePlaetze;
    ermaessigung = _ermaessigung;
  } // ctor

} // class StructKategorie
