package TicTakTicketCORBA.corbaTTT;

/**
* TicTakTicketCORBA/corbaTTT/StructKategorieHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaTTT.idl
* Dienstag, 19. November 2013 11:44 Uhr MEZ
*/

public final class StructKategorieHolder implements org.omg.CORBA.portable.Streamable
{
  public TicTakTicketCORBA.corbaTTT.StructKategorie value = null;

  public StructKategorieHolder ()
  {
  }

  public StructKategorieHolder (TicTakTicketCORBA.corbaTTT.StructKategorie initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TicTakTicketCORBA.corbaTTT.StructKategorieHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TicTakTicketCORBA.corbaTTT.StructKategorieHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TicTakTicketCORBA.corbaTTT.StructKategorieHelper.type ();
  }

}
