package CorbaServer;


/**
* TicTakTicket/corba/StructVeranstaltung.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Stefan Dietrich/Dropbox/team4/Corba/TicTakTicket.idl
* Dienstag, 19. November 2013 12:24 Uhr MEZ
*/

public final class StructVeranstaltung implements org.omg.CORBA.portable.IDLEntity
{
  public int vid = (int)0;
  public String vDatum = null;
  public String vName = null;
  public String vOrt = null;
  public String kuenstler = null;

  public StructVeranstaltung ()
  {
  } // ctor

  public StructVeranstaltung (int _vid, String _vDatum, String _vName, String _vOrt, String _kuenstler)
  {
    vid = _vid;
    vDatum = _vDatum;
    vName = _vName;
    vOrt = _vOrt;
    kuenstler = _kuenstler;
  } // ctor

} // class StructVeranstaltung
