package CorbaClient.ControllerInterfaces;

import CorbaClient.*;


/**
* TicTakTicket/corba/CorbaConterollerInterfacePackage/kategorieListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Stefan Dietrich/Dropbox/team4/Corba/TicTakTicket.idl
* Dienstag, 19. November 2013 11:59 Uhr MEZ
*/

public final class kategorieListHolder implements org.omg.CORBA.portable.Streamable
{
  public StructKategorie value[] = null;

  public kategorieListHolder ()
  {
  }

  public kategorieListHolder (StructKategorie[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = kategorieListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    kategorieListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return kategorieListHelper.type ();
  }

}
