package CorbaClient.ControllerInterfaces;

import CorbaClient.*;


/**
* TicTakTicket/corba/CorbaConterollerInterfacePackage/veranstaltungListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Stefan Dietrich/Dropbox/team4/Corba/TicTakTicket.idl
* Dienstag, 19. November 2013 11:59 Uhr MEZ
*/

public final class veranstaltungListHolder implements org.omg.CORBA.portable.Streamable
{
  public StructVeranstaltung value[] = null;

  public veranstaltungListHolder ()
  {
  }

  public veranstaltungListHolder (StructVeranstaltung[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = veranstaltungListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    veranstaltungListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return veranstaltungListHelper.type ();
  }

}
