/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUIController.MessageSchreibenCtrl;

/**
 *
 * @author Monika
 */
public class MessageSchreiben extends javax.swing.JFrame {
    private MessageSchreibenCtrl _ctrl;
    /**
     * Creates new form MessageSchreiben
     */
    public MessageSchreiben(MessageSchreibenCtrl ctrl) {
        _ctrl = ctrl;
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMessageScreen = new javax.swing.JPanel();
        jlblSreenTitle = new javax.swing.JLabel();
        jPanelMessagesWrite = new javax.swing.JPanel();
        jPanelMessageTitle = new javax.swing.JPanel();
        jlblMessageTitle = new javax.swing.JLabel();
        jtfMessageTitle = new javax.swing.JTextField();
        jPanelMessageText = new javax.swing.JPanel();
        jlblMessageText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMessageText = new javax.swing.JTextArea();
        jPanelMessageButton = new javax.swing.JPanel();
        jlblInfoMessage = new javax.swing.JLabel();
        jbtnSave = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanelMessageScreen.setLayout(new java.awt.GridLayout(3, 0));

        jlblSreenTitle.setText("Messages schreiben");
        jPanelMessageScreen.add(jlblSreenTitle);

        jPanelMessagesWrite.setLayout(new java.awt.GridLayout(2, 2));

        jPanelMessageTitle.setLayout(new java.awt.GridLayout(1, 2));

        jlblMessageTitle.setText("Message Titel");
        jPanelMessageTitle.add(jlblMessageTitle);
        jPanelMessageTitle.add(jtfMessageTitle);

        jPanelMessagesWrite.add(jPanelMessageTitle);

        jPanelMessageText.setLayout(new java.awt.GridLayout(1, 2));

        jlblMessageText.setText("Message Text");
        jPanelMessageText.add(jlblMessageText);

        jtaMessageText.setColumns(20);
        jtaMessageText.setRows(5);
        jScrollPane1.setViewportView(jtaMessageText);

        jPanelMessageText.add(jScrollPane1);

        jPanelMessagesWrite.add(jPanelMessageText);

        jPanelMessageScreen.add(jPanelMessagesWrite);

        jPanelMessageButton.setLayout(new java.awt.GridLayout(1, 2));
        jPanelMessageButton.add(jlblInfoMessage);

        jbtnSave.setText("Speichern");
        jbtnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSaveMouseClicked(evt);
            }
        });
        jPanelMessageButton.add(jbtnSave);

        jbtnCancel.setText("Cancel");
        jbtnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnCancelMouseClicked(evt);
            }
        });
        jPanelMessageButton.add(jbtnCancel);

        jPanelMessageScreen.add(jPanelMessageButton);

        getContentPane().add(jPanelMessageScreen);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCancelMouseClicked
        jbtnCancelClicked();
    }//GEN-LAST:event_jbtnCancelMouseClicked

    private void jbtnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSaveMouseClicked
        jbtnSaveClicked();
    }//GEN-LAST:event_jbtnSaveMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        jbtnCancelClicked();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelMessageButton;
    private javax.swing.JPanel jPanelMessageScreen;
    private javax.swing.JPanel jPanelMessageText;
    private javax.swing.JPanel jPanelMessageTitle;
    private javax.swing.JPanel jPanelMessagesWrite;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JLabel jlblInfoMessage;
    private javax.swing.JLabel jlblMessageText;
    private javax.swing.JLabel jlblMessageTitle;
    private javax.swing.JLabel jlblSreenTitle;
    private javax.swing.JTextArea jtaMessageText;
    private javax.swing.JTextField jtfMessageTitle;
    // End of variables declaration//GEN-END:variables
   
     public void Quit() {
        this.dispose();
    }

    private void jbtnCancelClicked() {
        
    }

    private void jbtnSaveClicked() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
