/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


/**
 *
 * @author Monika
 */
public class Selection extends javax.swing.JFrame {
    
   
    
    /**
     * Creates new form Selection
     */
    public Selection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelScreen = new javax.swing.JPanel();
        jPanelScreenTitle = new javax.swing.JPanel();
        jLabelScreenTitle = new javax.swing.JLabel();
        jPanelSelection = new javax.swing.JPanel();
        jButtonVsuchen = new javax.swing.JButton();
        jButtonKreservieren = new javax.swing.JButton();
        jButtonKverkaufen = new javax.swing.JButton();
        jButtonKuVerwalten = new javax.swing.JButton();
        jPanelInfoMessage = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jPanelScreen.setLayout(new java.awt.GridLayout(3, 1));

        jPanelScreenTitle.setLayout(new java.awt.GridLayout(1, 0));

        jLabelScreenTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelScreenTitle.setText("Wählen Sie aus Ihren Arbeitsbereichen");
        jPanelScreenTitle.add(jLabelScreenTitle);

        jPanelScreen.add(jPanelScreenTitle);

        jPanelSelection.setLayout(new java.awt.GridLayout(4, 2));

        jButtonVsuchen.setText("Veranstaltung suchen");
        jPanelSelection.add(jButtonVsuchen);

        jButtonKreservieren.setText("Karten reservieren");
        jPanelSelection.add(jButtonKreservieren);

        jButtonKverkaufen.setText("Karten verkaufen");
        jPanelSelection.add(jButtonKverkaufen);

        jButtonKuVerwalten.setText("Kunden verwalten");
        jPanelSelection.add(jButtonKuVerwalten);

        jPanelScreen.add(jPanelSelection);

        jPanelInfoMessage.setLayout(new java.awt.GridLayout(1, 0));
        jPanelScreen.add(jPanelInfoMessage);

        getContentPane().add(jPanelScreen);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKreservieren;
    private javax.swing.JButton jButtonKuVerwalten;
    private javax.swing.JButton jButtonKverkaufen;
    private javax.swing.JButton jButtonVsuchen;
    private javax.swing.JLabel jLabelScreenTitle;
    private javax.swing.JPanel jPanelInfoMessage;
    private javax.swing.JPanel jPanelScreen;
    private javax.swing.JPanel jPanelScreenTitle;
    private javax.swing.JPanel jPanelSelection;
    // End of variables declaration//GEN-END:variables
}
