package CorbaClient;

/**
* TicTakTicket/corba/CorbaConterollerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Stefan Dietrich/Dropbox/team4/Corba/TicTakTicket.idl
* Dienstag, 19. November 2013 11:59 Uhr MEZ
*/

public final class CorbaConterollerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaConterollerInterface value = null;

  public CorbaConterollerInterfaceHolder ()
  {
  }

  public CorbaConterollerInterfaceHolder (CorbaConterollerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaConterollerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaConterollerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaConterollerInterfaceHelper.type ();
  }

}
