package corba;


/**
* TicTakTicket/corba/CorbaConterollerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Stefan Dietrich/Dropbox/team4/Corba/TicTakTicket.idl
* Dienstag, 19. November 2013 15:21 Uhr MEZ
*/

public interface CorbaConterollerInterface extends CorbaConterollerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CorbaConterollerInterface
