package corba;

/**
* TicTakTicket/corba/StructKategorieHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Stefan Dietrich/Dropbox/team4/Corba/TicTakTicket.idl
* Dienstag, 19. November 2013 12:24 Uhr MEZ
*/

public final class StructKategorieHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.StructKategorie value = null;

  public StructKategorieHolder ()
  {
  }

  public StructKategorieHolder (corba.StructKategorie initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.StructKategorieHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.StructKategorieHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.StructKategorieHelper.type ();
  }

}
