package corba;

/**
* TicTakTicket/corba/StructVeranstaltungAnzeigenHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Stefan Dietrich/Dropbox/team4/Corba/TicTakTicket.idl
* Dienstag, 19. November 2013 15:21 Uhr MEZ
*/

public final class StructVeranstaltungAnzeigenHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.StructVeranstaltungAnzeigen value = null;

  public StructVeranstaltungAnzeigenHolder ()
  {
  }

  public StructVeranstaltungAnzeigenHolder (corba.StructVeranstaltungAnzeigen initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.StructVeranstaltungAnzeigenHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.StructVeranstaltungAnzeigenHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.StructVeranstaltungAnzeigenHelper.type ();
  }

}
