package corba;


/**
* TicTakTicket/corba/StructKategorieKarte.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Stefan Dietrich/Dropbox/team4/Corba/TicTakTicket.idl
* Dienstag, 19. November 2013 15:21 Uhr MEZ
*/

public final class StructKategorieKarte implements org.omg.CORBA.portable.IDLEntity
{
  public corba.StructKarte kartenList[] = null;

  public StructKategorieKarte ()
  {
  } // ctor

  public StructKategorieKarte (corba.StructKarte[] _kartenList)
  {
    kartenList = _kartenList;
  } // ctor

} // class StructKategorieKarte
