package TicTakTicketCORBA.corbaTTT.CorbaConterollerInterfacePackage;


/**
* TicTakTicketCORBA/corbaTTT/CorbaConterollerInterfacePackage/karteListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaTTT.idl
* Dienstag, 19. November 2013 11:44 Uhr MEZ
*/

public final class karteListHolder implements org.omg.CORBA.portable.Streamable
{
  public TicTakTicketCORBA.corbaTTT.StructKarte value[] = null;

  public karteListHolder ()
  {
  }

  public karteListHolder (TicTakTicketCORBA.corbaTTT.StructKarte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TicTakTicketCORBA.corbaTTT.CorbaConterollerInterfacePackage.karteListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TicTakTicketCORBA.corbaTTT.CorbaConterollerInterfacePackage.karteListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TicTakTicketCORBA.corbaTTT.CorbaConterollerInterfacePackage.karteListHelper.type ();
  }

}
