package TicTakTicketCORBA.corbaTTT.CorbaConterollerInterfacePackage;


/**
* TicTakTicketCORBA/corbaTTT/CorbaConterollerInterfacePackage/veranstaltungListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaTTT.idl
* Dienstag, 19. November 2013 09:05 Uhr MEZ
*/

public final class veranstaltungListHolder implements org.omg.CORBA.portable.Streamable
{
  public TicTakTicketCORBA.corbaTTT.StructVernastaltung value[] = null;

  public veranstaltungListHolder ()
  {
  }

  public veranstaltungListHolder (TicTakTicketCORBA.corbaTTT.StructVernastaltung[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TicTakTicketCORBA.corbaTTT.CorbaConterollerInterfacePackage.veranstaltungListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TicTakTicketCORBA.corbaTTT.CorbaConterollerInterfacePackage.veranstaltungListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TicTakTicketCORBA.corbaTTT.CorbaConterollerInterfacePackage.veranstaltungListHelper.type ();
  }

}
